/* eslint-disable */
// Kleap MOTION RUNTIME — a declarative, time-driven animation engine (the model
// composes SCENES on top of this; it never re-implements the mechanics).
//
// Model: every frame is a PURE FUNCTION OF THE PLAYHEAD. <Stage duration={N}> owns
// a clock (seconds); any child reads it via useTime(), or wraps content in
// <Sprite start end> to only render in a window (with localTime + progress 0..1).
// Because nothing is an imperative tween, SCRUBBING IS ALWAYS CORRECT and there is
// no "does it reverse" problem — at time t the render is f(t), deterministic.
//
// The Kleap preview player drives this through a `window.__kleapTimeline` shim the
// Stage installs (same interface the player already speaks: play/pause/seek/progress/
// time/duration). The Stage does NOT draw its own controls — the player provides them.
//
// 🚫 DO NOT EDIT THIS FILE. Build your film in src/components/anim/Film.tsx by
//    composing <Stage> + <Sprite>/<TextSprite>/<ImageSprite>/<RectSprite> + Easing.
import React from "react";

// ── helpers ──────────────────────────────────────────────────────────────────
export const clamp = (v: number, min: number, max: number) =>
  Math.max(min, Math.min(max, v));

// Common helpers the model reaches for (counters, clocks, repeated rows). Exported
// so a film's natural `import { …, pad } from "./Stage"` always resolves.
export const lerp = (a: number, b: number, t: number) => a + (b - a) * t;
export const pad = (n: number, width = 2) =>
  String(Math.trunc(Math.abs(n))).padStart(width, "0");
export const range = (n: number) =>
  Array.from({ length: Math.max(0, n | 0) }, (_, i) => i);
export const round = (n: number, dp = 0) => {
  const f = Math.pow(10, dp);
  return Math.round(n * f) / f;
};

// Easings take t∈[0,1] → eased t (back/elastic may overshoot).
export const Easing = {
  linear: (t: number) => t,
  easeInQuad: (t: number) => t * t,
  easeOutQuad: (t: number) => t * (2 - t),
  easeInOutQuad: (t: number) => (t < 0.5 ? 2 * t * t : -1 + (4 - 2 * t) * t),
  easeInCubic: (t: number) => t * t * t,
  easeOutCubic: (t: number) => --t * t * t + 1,
  easeInOutCubic: (t: number) =>
    t < 0.5 ? 4 * t * t * t : (t - 1) * (2 * t - 2) * (2 * t - 2) + 1,
  easeInQuart: (t: number) => t * t * t * t,
  easeOutQuart: (t: number) => 1 - --t * t * t * t,
  easeInExpo: (t: number) => (t === 0 ? 0 : Math.pow(2, 10 * (t - 1))),
  easeOutExpo: (t: number) => (t === 1 ? 1 : 1 - Math.pow(2, -10 * t)),
  easeInOutExpo: (t: number) => {
    if (t === 0) return 0;
    if (t === 1) return 1;
    if (t < 0.5) return 0.5 * Math.pow(2, 20 * t - 10);
    return 1 - 0.5 * Math.pow(2, -20 * t + 10);
  },
  easeInSine: (t: number) => 1 - Math.cos((t * Math.PI) / 2),
  easeOutSine: (t: number) => Math.sin((t * Math.PI) / 2),
  easeInOutSine: (t: number) => -(Math.cos(Math.PI * t) - 1) / 2,
  easeOutBack: (t: number) => {
    const c1 = 1.70158,
      c3 = c1 + 1;
    return 1 + c3 * Math.pow(t - 1, 3) + c1 * Math.pow(t - 1, 2);
  },
  easeInBack: (t: number) => {
    const c1 = 1.70158,
      c3 = c1 + 1;
    return c3 * t * t * t - c1 * t * t;
  },
  easeOutElastic: (t: number) => {
    const c4 = (2 * Math.PI) / 3;
    if (t === 0) return 0;
    if (t === 1) return 1;
    return Math.pow(2, -10 * t) * Math.sin((t * 10 - 0.75) * c4) + 1;
  },
} as const;

type EaseFn = (t: number) => number;

// interpolate([0,.5,1],[0,100,50], ease?) → fn(t). Maps t across keyframes to values.
export function interpolate(
  input: number[],
  output: number[],
  ease: EaseFn | EaseFn[] = Easing.linear,
) {
  return (t: number) => {
    if (t <= input[0]) return output[0];
    if (t >= input[input.length - 1]) return output[output.length - 1];
    for (let i = 0; i < input.length - 1; i++) {
      if (t >= input[i] && t <= input[i + 1]) {
        const span = input[i + 1] - input[i];
        const local = span === 0 ? 0 : (t - input[i]) / span;
        const fn = Array.isArray(ease) ? ease[i] || Easing.linear : ease;
        return output[i] + (output[i + 1] - output[i]) * fn(local);
      }
    }
    return output[output.length - 1];
  };
}

// animate({from,to,start,end,ease})(t) — single-segment tween over the playhead.
export function animate({
  from = 0,
  to = 1,
  start = 0,
  end = 1,
  ease = Easing.easeInOutCubic,
}: {
  from?: number;
  to?: number;
  start?: number;
  end?: number;
  ease?: EaseFn;
}) {
  return (t: number) => {
    if (t <= start) return from;
    if (t >= end) return to;
    return from + (to - from) * ease((t - start) / (end - start));
  };
}

// ── timeline context ───────────────────────────────────────────────────────────
type TL = { time: number; duration: number; playing: boolean };
const TimelineContext = React.createContext<TL>({
  time: 0,
  duration: 10,
  playing: false,
});
export const useTime = () => React.useContext(TimelineContext).time;
export const useTimeline = () => React.useContext(TimelineContext);

// ── Sprite (time window) ────────────────────────────────────────────────────────
type SpriteCtx = {
  localTime: number;
  progress: number;
  duration: number;
  visible: boolean;
};
const SpriteContext = React.createContext<SpriteCtx>({
  localTime: 0,
  progress: 0,
  duration: 0,
  visible: false,
});
export const useSprite = () => React.useContext(SpriteContext);

export function Sprite({
  start = 0,
  end = Infinity,
  children,
  keepMounted = false,
}: {
  start?: number;
  end?: number;
  keepMounted?: boolean;
  children: React.ReactNode | ((ctx: SpriteCtx) => React.ReactNode);
}) {
  const { time } = useTimeline();
  const visible = time >= start && time <= end;
  if (!visible && !keepMounted) return null;
  const duration = end - start;
  const localTime = Math.max(0, time - start);
  const progress =
    duration > 0 && isFinite(duration) ? clamp(localTime / duration, 0, 1) : 0;
  const value: SpriteCtx = { localTime, progress, duration, visible };
  return (
    <SpriteContext.Provider value={value}>
      {typeof children === "function" ? (children as any)(value) : children}
    </SpriteContext.Provider>
  );
}

// ── ready-made sprites ──────────────────────────────────────────────────────────
export function TextSprite({
  text,
  x = 0,
  y = 0,
  size = 48,
  color = "#111",
  font = "Inter, system-ui, sans-serif",
  weight = 600,
  entryDur = 0.45,
  exitDur = 0.35,
  entryEase = Easing.easeOutBack,
  exitEase = Easing.easeInCubic,
  align = "left",
  letterSpacing = "-0.01em",
}: any) {
  const { localTime, duration } = useSprite();
  const exitStart = Math.max(0, duration - exitDur);
  let opacity = 1,
    ty = 0;
  if (localTime < entryDur) {
    const t = entryEase(clamp(localTime / entryDur, 0, 1));
    opacity = t;
    ty = (1 - t) * 16;
  } else if (localTime > exitStart) {
    const t = exitEase(clamp((localTime - exitStart) / exitDur, 0, 1));
    opacity = 1 - t;
    ty = -t * 8;
  }
  const tx = align === "center" ? "-50%" : align === "right" ? "-100%" : "0";
  return (
    <div
      style={{
        position: "absolute",
        left: x,
        top: y,
        transform: `translate(${tx}, ${ty}px)`,
        opacity,
        fontFamily: font,
        fontSize: size,
        fontWeight: weight,
        color,
        letterSpacing,
        whiteSpace: "pre",
        lineHeight: 1.1,
        willChange: "transform, opacity",
      }}
    >
      {text}
    </div>
  );
}

export function ImageSprite({
  src,
  x = 0,
  y = 0,
  width = 400,
  height = 300,
  entryDur = 0.6,
  exitDur = 0.4,
  kenBurns = false,
  kenBurnsScale = 1.08,
  radius = 12,
  fit = "cover",
}: any) {
  const { localTime, duration } = useSprite();
  const exitStart = Math.max(0, duration - exitDur);
  let opacity = 1,
    scale = 1;
  if (localTime < entryDur) {
    const t = Easing.easeOutCubic(clamp(localTime / entryDur, 0, 1));
    opacity = t;
    scale = 0.96 + 0.04 * t;
  } else if (localTime > exitStart) {
    const t = Easing.easeInCubic(
      clamp((localTime - exitStart) / exitDur, 0, 1),
    );
    opacity = 1 - t;
    scale = (kenBurns ? kenBurnsScale : 1) + 0.02 * t;
  } else if (kenBurns) {
    const holdSpan = exitStart - entryDur;
    const holdT = holdSpan > 0 ? (localTime - entryDur) / holdSpan : 0;
    scale = 1 + (kenBurnsScale - 1) * holdT;
  }
  return (
    <div
      style={{
        position: "absolute",
        left: x,
        top: y,
        width,
        height,
        opacity,
        transform: `scale(${scale})`,
        transformOrigin: "center",
        borderRadius: radius,
        overflow: "hidden",
        willChange: "transform, opacity",
      }}
    >
      <img
        src={src}
        alt=""
        style={{
          width: "100%",
          height: "100%",
          objectFit: fit,
          display: "block",
        }}
      />
    </div>
  );
}

export function RectSprite({
  x = 0,
  y = 0,
  width = 100,
  height = 100,
  color = "#111",
  radius = 8,
  entryDur = 0.4,
  exitDur = 0.3,
  render,
}: any) {
  const ctx = useSprite();
  const { localTime, duration } = ctx;
  const exitStart = Math.max(0, duration - exitDur);
  let opacity = 1,
    scale = 1;
  if (localTime < entryDur) {
    const t = Easing.easeOutBack(clamp(localTime / entryDur, 0, 1));
    opacity = clamp(localTime / entryDur, 0, 1);
    scale = 0.4 + 0.6 * t;
  } else if (localTime > exitStart) {
    const t = Easing.easeInQuad(clamp((localTime - exitStart) / exitDur, 0, 1));
    opacity = 1 - t;
    scale = 1 - 0.15 * t;
  }
  const overrides = render ? render(ctx) : {};
  return (
    <div
      style={{
        position: "absolute",
        left: x,
        top: y,
        width,
        height,
        background: color,
        borderRadius: radius,
        opacity,
        transform: `scale(${scale})`,
        transformOrigin: "center",
        willChange: "transform, opacity",
        ...overrides,
      }}
    />
  );
}

// ── Stage (clock + viewport scaler + __kleapTimeline bridge, NO own controls) ───
export function Stage({
  width = 1280,
  height = 720,
  duration = 10,
  background = "#0a0a0a",
  loop = true,
  autoplay = true,
  children,
}: {
  width?: number;
  height?: number;
  duration?: number;
  background?: string;
  loop?: boolean;
  autoplay?: boolean;
  children: React.ReactNode;
}) {
  // Respect reduced motion for the DEPLOYED site's autoplay default ONLY.
  //
  // Inside an iframe we are in a Kleap surface (the builder preview pane / an
  // embed), where the film IS the artifact being authored: freezing it on the
  // last frame made the whole animation format look broken for every designer
  // with "Reduce motion" enabled at the OS level — the film never moved and
  // there was nothing to click. So: in-iframe ALWAYS animates, top-level keeps
  // the accessibility default (parked on the final frame, paused). Either way
  // the clock + __kleapTimeline bridge exist, so the player is never dead and a
  // reduced-motion visitor can still press play (play() rewinds from the end).
  const inKleapSurface =
    typeof window !== "undefined" && window.self !== window.top;
  const reduced =
    !inKleapSurface &&
    typeof window !== "undefined" &&
    !!window.matchMedia &&
    window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const [time, setTime] = React.useState(reduced ? duration : 0);
  const [playing, setPlaying] = React.useState(autoplay && !reduced);
  const [scale, setScale] = React.useState(1);
  const hostRef = React.useRef<HTMLDivElement>(null);
  const rafRef = React.useRef<number | null>(null);
  const lastTs = React.useRef<number | null>(null);
  const cbRef = React.useRef<{ update?: () => void; complete?: () => void }>(
    {},
  );

  // Auto-scale the fixed canvas to fit the host (the Kleap player iframe).
  React.useEffect(() => {
    const el = hostRef.current;
    if (!el) return;
    const measure = () =>
      setScale(
        Math.max(
          0.02,
          Math.min(el.clientWidth / width, el.clientHeight / height),
        ),
      );
    measure();
    const ro = new ResizeObserver(measure);
    ro.observe(el);
    return () => ro.disconnect();
  }, [width, height]);

  // rAF clock.
  React.useEffect(() => {
    if (!playing) {
      lastTs.current = null;
      return;
    }
    const step = (ts: number) => {
      if (lastTs.current == null) lastTs.current = ts;
      const dt = (ts - lastTs.current) / 1000;
      lastTs.current = ts;
      setTime((t) => {
        let next = t + dt;
        if (next >= duration) {
          if (loop) next = next % duration;
          else {
            next = duration;
            setPlaying(false);
            cbRef.current.complete && cbRef.current.complete();
          }
        }
        return next;
      });
      rafRef.current = requestAnimationFrame(step);
    };
    rafRef.current = requestAnimationFrame(step);
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      lastTs.current = null;
    };
  }, [playing, duration, loop]);

  // Notify the player's onUpdate each time the playhead changes.
  React.useEffect(() => {
    cbRef.current.update && cbRef.current.update();
  }, [time]);

  // Install the window.__kleapTimeline shim — the SAME interface the Kleap player
  // already drives (gsap-like). progress() is an overloaded getter/setter.
  React.useEffect(() => {
    // Two units, two entry points — mirroring gsap, which the Kleap player and
    // any AI-written control code both assume:
    //   seekProgress(0..1)  ← progress()
    //   seekSeconds(0..dur) ← seek()
    // They used to share ONE 0..1 implementation, so seek(6) on an 8s film was
    // clamped to 1 and jumped to the last frame instead of 6s in.
    const seekProgress = (v: number) => {
      setPlaying(false);
      setTime(clamp(v, 0, 1) * duration);
    };
    const seekSeconds = (v: number) => {
      setPlaying(false);
      setTime(clamp(v, 0, duration));
    };
    const tl: any = {
      duration: () => duration,
      time: () => time,
      paused: () => !playing,
      progress: (v?: number) => {
        if (v === undefined) return duration > 0 ? time / duration : 0;
        seekProgress(v);
        return tl;
      },
      play: () => {
        if (time >= duration - 0.001) setTime(0);
        setPlaying(true);
        return tl;
      },
      pause: () => {
        setPlaying(false);
        return tl;
      },
      restart: () => {
        setTime(0);
        setPlaying(true);
        return tl;
      },
      seek: (v: number) => {
        seekSeconds(v);
        return tl;
      },
      eventCallback: (name: string, fn: () => void) => {
        if (name === "onUpdate") cbRef.current.update = fn;
        else if (name === "onComplete") cbRef.current.complete = fn;
        return tl;
      },
      kill: () => {},
    };
    (window as any).__kleapTimeline = tl;
    return () => {
      if ((window as any).__kleapTimeline === tl)
        (window as any).__kleapTimeline = null;
    };
    // re-install when the closed-over time/duration/playing change so getters are fresh
  }, [time, duration, playing]);

  // Announce the film to the Kleap preview ONCE per mount so the player controls
  // can appear the instant the island hydrates (the pane also polls, this just
  // removes the lag). Guarded by a ref because the bridge above re-installs on
  // every tick — without it this would post a message per frame. No-op on the
  // deployed site: nobody is listening.
  const announcedRef = React.useRef(false);
  React.useEffect(() => {
    if (announcedRef.current) return;
    announcedRef.current = true;
    try {
      window.parent?.postMessage(
        { type: "kleap-timeline-ready", duration },
        "*",
      );
    } catch {}
  }, [duration]);

  const ctx = React.useMemo(
    () => ({ time, duration, playing }),
    [time, duration, playing],
  );

  return (
    <div
      ref={hostRef}
      style={{
        position: "absolute",
        inset: 0,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
        background: "#000",
      }}
    >
      <div
        style={{
          width,
          height,
          background,
          position: "relative",
          transform: `scale(${scale})`,
          transformOrigin: "center",
          flexShrink: 0,
          overflow: "hidden",
        }}
      >
        <TimelineContext.Provider value={ctx}>
          {children}
        </TimelineContext.Provider>
        {/* A reduced-motion visitor gets the film parked on its final frame —
            the right default, but on a page whose whole content IS the film it
            reads as a broken still with nothing to click. The Kleap builder has
            a player; a published page has none, so the runtime offers its own
            way in. Shown ONLY when the OS asked for reduced motion, so it never
            appears over an autoplaying film. */}
        {reduced && !playing && (
          <button
            type="button"
            aria-label="Play"
            onClick={() => {
              if (time >= duration - 0.001) setTime(0);
              setPlaying(true);
            }}
            style={{
              position: "absolute",
              inset: 0,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              background: "rgba(0,0,0,.35)",
              border: 0,
              cursor: "pointer",
            }}
          >
            <span
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                width: 88,
                height: 88,
                borderRadius: "50%",
                background: "rgba(255,255,255,.92)",
                boxShadow: "0 8px 30px rgba(0,0,0,.35)",
              }}
            >
              <svg width="32" height="32" viewBox="0 0 24 24" fill="#111">
                <path d="M8 5v14l11-7z" />
              </svg>
            </span>
          </button>
        )}
      </div>
    </div>
  );
}
